repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Apply the rustfmt style
        entry: cargo fmt --all -- --color always
        language: system
        pass_filenames: false
      - id: clippy
        name: clippy
        description: Check clippy for lints
        entry: cargo clippy --frozen
        language: system
        pass_filenames: false
      - id: test
        name: test
        description: run unit and doc tests
        entry: cargo test
        language: system
        pass_filenames: false