repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Apply the rustfmt style
        entry: cargo fmt --all -- --color always
        language: system
        pass_filenames: false